import './globals.css'

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { NextUIProvider } from '@nextui-org/react'

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="customTheme bg-zinc-900 min-h-screen">
        <div className="w-full px-3 mx-auto sm:w-3/4 md:w-3/5">
          <NextUIProvider>{children}</NextUIProvider>
        </div>
      </body>
    </html>
  )
}
